In [1]:
import numpy as np
import pandas as pd

In [2]:
var = []
for i in range(1, 5):
    var.append(np.random.randn(10))

In [3]:
var

[array([-1.38794136,  0.06111014, -0.43533479,  0.28774957,  1.25472689,
         0.43061538, -1.43161533, -0.76150247, -0.86182293,  0.50176914]),
 array([-0.79039543, -0.8471555 , -0.86898833, -1.55778883,  0.32996202,
        -0.52954841, -1.85394385,  0.35278724,  0.20582409,  0.0432222 ]),
 array([ 0.85832414,  0.31265151, -0.37642964,  1.41108331, -1.5946581 ,
         0.87442979, -1.56672134,  1.67282644,  0.26494401, -0.12140464]),
 array([ 1.00061468, -1.08791077,  0.26155639,  0.3494157 , -0.63085407,
         1.99916864,  0.84720016,  0.59726546,  1.64562583,  1.31440367])]

In [6]:
np.array(var)

array([[-1.38794136,  0.06111014, -0.43533479,  0.28774957,  1.25472689,
         0.43061538, -1.43161533, -0.76150247, -0.86182293,  0.50176914],
       [-0.79039543, -0.8471555 , -0.86898833, -1.55778883,  0.32996202,
        -0.52954841, -1.85394385,  0.35278724,  0.20582409,  0.0432222 ],
       [ 0.85832414,  0.31265151, -0.37642964,  1.41108331, -1.5946581 ,
         0.87442979, -1.56672134,  1.67282644,  0.26494401, -0.12140464],
       [ 1.00061468, -1.08791077,  0.26155639,  0.3494157 , -0.63085407,
         1.99916864,  0.84720016,  0.59726546,  1.64562583,  1.31440367]])